[package]
name = "modern_robotics_rust"
version = "0.1.0"
edition = "2024"

[dependencies]
nalgebra = "0.34.1"
csv = "1.4.0"
miniplot = { version = "0.0.1", optional = true }
#nalgebra-lapack = { version = "0.25", features = ["openblas"] } #

[features]
default = []
plot = ["miniplot"]
